# Generated by Django 4.2.26 on 2025-11-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_trim_quant_rating_filters"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="investment",
            options={"ordering": ["ticker"]},
        ),
        migrations.RemoveField(
            model_name="investment",
            name="name",
        ),
        migrations.RemoveField(
            model_name="investment",
            name="risk_level",
        ),
        migrations.AddField(
            model_name="investment",
            name="market_cap",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=24, null=True
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="volume",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="investment",
            name="ticker",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
