# Generated by Django 4.2.26 on 2025-11-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_investment_options_remove_investment_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="investment",
            name="market_cap",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=30, null=True
            ),
        ),
    ]
