# Generated by Django 4.2.26 on 2025-11-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_investment_options_remove_investment_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="investment",
            name="options_suitability",
            field=models.BooleanField(default=False),
        ),
    ]
