# Generated by Django 4.2.26 on 2025-11-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_investment_options_suitability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investment",
            name="options_suitability",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
