# Generated by Django 4.2.26 on 2025-11-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_investment_options_suitability"),
    ]

    operations = [
        migrations.AddField(
            model_name="investment",
            name="screenter_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
