# Generated by Django 4.2.27 on 2025-12-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_rename_screenter_type_to_screener_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="investment",
            name="option_exp",
            field=models.DateField(blank=True, null=True),
        ),
    ]
