# Generated by Django 4.2.27 on 2025-12-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_investment_option_exp"),
    ]

    operations = [
        migrations.AddField(
            model_name="investment",
            name="opt_val",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
    ]
