# Generated by Django 4.2.27 on 2026-01-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_investment_opt_val"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=25)),
                ("target_currency", models.CharField(default="USD", max_length=10)),
                ("period_type", models.CharField(default="annual", max_length=20)),
                (
                    "statement_type",
                    models.CharField(default="income-statement", max_length=50),
                ),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": [
                    "symbol",
                    "period_type",
                    "statement_type",
                    "target_currency",
                ],
                "unique_together": {
                    ("symbol", "period_type", "statement_type", "target_currency")
                },
            },
        ),
    ]
