# Generated by Django 4.2.27 on 2026-01-08 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_financialstatement"),
    ]

    operations = [
        migrations.RenameField(
            model_name="investment",
            old_name="opt_val",
            new_name="roi",
        ),
    ]
