# Generated by Django 4.2.27 on 2025-12-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_duediligencereport"),
    ]

    operations = [
        migrations.AddField(
            model_name="investment",
            name="weekly_options",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
