# Generated by Django 4.2.26 on 2025-11-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_duediligencereport"),
    ]

    operations = [
        migrations.AddField(
            model_name="investment",
            name="rsi",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
