# Generated by Django 4.2.26 on 2025-11-22 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_rename_investment_opt_val_to_roi"),
        ("api", "0014_investment_delta"),
    ]

    operations = []
