# Generated by Django 4.2.27 on 2025-12-03 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_investment_weekly_options"),
        ("api", "0015_merge_0012_0014"),
    ]

    operations = []
