# Generated by ChatGPT on 2025-02-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_cboe_security"),
    ]

    operations = [
        migrations.AlterField(
            model_name="screenerfilter",
            name="label",
            field=models.TextField(),
        ),
    ]
