# Generated by Django 4.2.26 on 2025-11-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_alter_screenerfilter_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investment",
            name="ticker",
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name="investment",
            constraint=models.UniqueConstraint(
                fields=("ticker", "screener_type"),
                name="unique_investment_ticker_screener_type",
            ),
        ),
    ]
