# Generated by Django 4.2.25 on 2026-01-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_merge_0013_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='strike_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
    ]
