# Generated by Django 4.2.25 on 2026-01-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_investment_strike_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="investment",
            name="next_earnings_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
