# Generated by Django 4.2.25 on 2026-02-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_investment_deprecated_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=50, unique=True)),
                ('exchange', models.CharField(blank=True, default='', max_length=100)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ticker'],
            },
        ),
    ]
