# Generated by Django 4.2.25 on 2026-02-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_symbol_put_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='ask',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='bid',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='mid',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='option_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
