# Generated by Django 4.2.25 on 2026-02-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_symbol_bid_ask_mid_option_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='roi',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
    ]
