# Generated by Django 4.2.25 on 2026-03-28 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0037_emailverificationtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBriefEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition_date', models.DateField(db_index=True, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('body_text', models.TextField()),
                ('top_symbols', models.JSONField(blank=True, default=list)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-edition_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyBriefSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_verification', 'Pending verification'), ('active', 'Active'), ('unsubscribed', 'Unsubscribed')], db_index=True, default='unsubscribed', max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('source', models.CharField(blank=True, choices=[('', 'Unknown'), ('signup', 'Signup'), ('daily_brief_cta', 'Daily brief CTA'), ('profile', 'Profile')], db_index=True, default='', max_length=32)),
                ('subscribed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_brief_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-subscribed_at', 'user_id'],
            },
        ),
    ]
