# Generated by Django 4.2.25 on 2026-03-31 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_symbol_technical_score_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition_date', models.DateField(db_index=True)),
                ('rank', models.PositiveSmallIntegerField()),
                ('ticker', models.CharField(db_index=True, max_length=50)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('rsi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('roi', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('delta', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('is_alternative', models.BooleanField(db_index=True, default=False)),
                ('option_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_briefs', to='api.symbol')),
            ],
            options={
                'ordering': ['-edition_date', 'rank', 'ticker'],
            },
        ),
        migrations.AddConstraint(
            model_name='dailybrief',
            constraint=models.UniqueConstraint(fields=('edition_date', 'rank'), name='unique_daily_brief_rank_per_day'),
        ),
        migrations.AddConstraint(
            model_name='dailybrief',
            constraint=models.UniqueConstraint(fields=('edition_date', 'symbol'), name='unique_daily_brief_symbol_per_day'),
        ),
    ]
