# Generated by Django 4.2.25 on 2026-06-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_rename_paddle_to_stripe'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='call_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
