"""
Django settings for investing_project project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import json
import os
from datetime import timedelta

import dj_database_url
from corsheaders.defaults import default_headers
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()


def _load_json_env(name: str, default):
    raw_value = os.getenv(name, "").strip()
    if not raw_value:
        return default
    try:
        parsed = json.loads(raw_value)
    except json.JSONDecodeError:
        return default
    return parsed if isinstance(parsed, type(default)) else default


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY", "django-insecure-@^$l03hdb8%d%#eo=k*+qdjq94u-5fmbnmlr6)m5yfuh8@nhvi"
)

OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
GEMINI_OPENAI_BASE_URL = os.getenv(
    "GEMINI_OPENAI_BASE_URL",
    "https://generativelanguage.googleapis.com/v1beta/openai/",
)
AGENT_MODEL_PROVIDER = os.getenv("AGENT_MODEL_PROVIDER", "anthropic").lower()
AGENT_MODEL = os.getenv(
    "AGENT_MODEL",
    (
        "claude-sonnet-4-5"
        if AGENT_MODEL_PROVIDER == "anthropic"
        else "gemini-2.5-flash"
        if AGENT_MODEL_PROVIDER == "gemini"
        else "gpt-4.1-mini"
    ),
)
AGENT_ANTHROPIC_MAX_TOKENS = int(os.getenv("AGENT_ANTHROPIC_MAX_TOKENS", "4096"))
AGENT_MAX_ITERATIONS = int(os.getenv("AGENT_MAX_ITERATIONS", "10"))
AGENT_OPENAI_TIMEOUT_SECONDS = int(os.getenv("AGENT_OPENAI_TIMEOUT_SECONDS", "45"))
AGENT_OVERALL_TIMEOUT_SECONDS = int(os.getenv("AGENT_OVERALL_TIMEOUT_SECONDS", "90"))
AGENT_OPENAI_MAX_RETRIES = int(os.getenv("AGENT_OPENAI_MAX_RETRIES", "1"))
LLM_MODEL_PRICING_PER_1M_TOKENS = _load_json_env(
    "LLM_MODEL_PRICING_PER_1M_TOKENS_JSON",
    {},
)
LLM_WEB_SEARCH_COST_PER_CALL = _load_json_env("LLM_WEB_SEARCH_COST_PER_CALL_JSON", {})
LLM_WEB_SEARCH_FIXED_INPUT_TOKENS = _load_json_env(
    "LLM_WEB_SEARCH_FIXED_INPUT_TOKENS_JSON",
    {},
)

RAPIDAPI_KEY = os.getenv('RAPIDAPI_KEY')
FINANCIAL_MODELING_API_KEY = os.getenv('FINANCIAL_MODELING_API_KEY')  # still used by initial_screener / put_checker



# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() in {"1", "true", "yes"}
APP_ENV = os.getenv("APP_ENV", "development").lower()
IS_PRODUCTION = APP_ENV == "production"
DEFAULT_APP_PORT = "8080" if IS_PRODUCTION else "8000"
APP_PORT = int(os.getenv("PORT", DEFAULT_APP_PORT))
LOCAL_API_BASE_URL = os.getenv("LOCAL_API_BASE_URL", f"http://127.0.0.1:{APP_PORT}")

DEFAULT_ALLOWED_HOSTS = [
    "api.putpulse.com",
    ".railway.app",
    "localhost",
    "127.0.0.1",
    "testserver",
]

allowed_hosts_env = os.getenv("ALLOWED_HOSTS")
if allowed_hosts_env:
    ALLOWED_HOSTS = DEFAULT_ALLOWED_HOSTS + [
        host.strip()
        for host in allowed_hosts_env.split(",")
        if host.strip() and host.strip() not in DEFAULT_ALLOWED_HOSTS
    ]
else:
    ALLOWED_HOSTS = DEFAULT_ALLOWED_HOSTS.copy()

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True
SECURE_SSL_REDIRECT = False


CORS_ALLOWED_ORIGINS = [
    "http://localhost:4173",
    # optional if you also hit it from other places:
    "http://localhost:8000",
    "http://localhost:8080",
    "https://putpulse.com",
    "https://www.putpulse.com",
    "http://127.0.0.1:4173",
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    *default_headers,
    "x-device-fingerprint",
]

CSRF_TRUSTED_ORIGINS = [
    "https://putpulse.com",
    "https://www.putpulse.com",
    "https://api.putpulse.com",
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "django_celery_beat",
    "api",
]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": True,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.FormParser",
    ],
}

AUTH_REFRESH_COOKIE_NAME = os.getenv("AUTH_REFRESH_COOKIE_NAME", "refresh_token")
AUTH_REFRESH_COOKIE_SECURE = os.getenv(
    "AUTH_REFRESH_COOKIE_SECURE", str(IS_PRODUCTION)
).lower() in {"1", "true", "yes"}
AUTH_REFRESH_COOKIE_SAMESITE = os.getenv("AUTH_REFRESH_COOKIE_SAMESITE", "Lax")
AUTH_REFRESH_COOKIE_PATH = os.getenv("AUTH_REFRESH_COOKIE_PATH", "/api/auth/")
AUTH_REFRESH_COOKIE_DOMAIN = os.getenv("AUTH_REFRESH_COOKIE_DOMAIN") or None
AUTH_REFRESH_COOKIE_MAX_AGE = int(os.getenv("AUTH_REFRESH_COOKIE_MAX_AGE", str(30 * 24 * 60 * 60)))
AUTH_ALLOW_PUBLIC_REGISTRATION = os.getenv(
    "AUTH_ALLOW_PUBLIC_REGISTRATION", "False"
).lower() in {"1", "true", "yes"}
AUTH_EMAIL_VERIFICATION_HOURS = int(os.getenv("AUTH_EMAIL_VERIFICATION_HOURS", "24"))
FRONTEND_BASE_URL = os.getenv("FRONTEND_BASE_URL", "http://localhost:4173")
AUTH_VERIFY_EMAIL_PATH = os.getenv("AUTH_VERIFY_EMAIL_PATH", "/verify-email")
AUTH_RESEND_COOLDOWN_SECONDS = int(os.getenv("AUTH_RESEND_COOLDOWN_SECONDS", "60"))

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=int(os.getenv("AUTH_ACCESS_TOKEN_MINUTES", "15"))
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=int(os.getenv("AUTH_REFRESH_TOKEN_DAYS", "7"))
    ),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    (
        "django.core.mail.backends.smtp.EmailBackend"
        if IS_PRODUCTION
        else "django.core.mail.backends.console.EmailBackend"
    ),
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() in {"1", "true", "yes"}
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "False").lower() in {"1", "true", "yes"}
EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT", "20"))
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "admin@putpulse.com")
CONTACT_EMAIL = os.getenv("CONTACT_EMAIL", "support@putpulse.com")
# Comma-separated recipient list for paid Pro invoice notifications.
# Defaults to the support address so existing deployments keep a sensible target.
BILLING_NOTIFICATION_EMAIL = os.getenv("BILLING_NOTIFICATION_EMAIL", CONTACT_EMAIL)
RESEND_API_KEY = os.getenv("RESEND_API_KEY")
RESEND_API_URL = os.getenv("RESEND_API_URL", "https://api.resend.com/emails")
RESEND_FROM_EMAIL = os.getenv("RESEND_FROM_EMAIL", DEFAULT_FROM_EMAIL)

STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY", "")
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET", "")

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "investing_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "investing_project.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASE_URL = os.getenv("DATABASE_URL")

if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    }
elif os.getenv("PGHOST"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("PGDATABASE"),
            "USER": os.getenv("PGUSER"),
            "PASSWORD": os.getenv("PGPASSWORD"),
            "HOST": os.getenv("PGHOST"),
            "PORT": os.getenv("PGPORT", "5432"),
        }
    }
elif os.getenv("POSTGRES_HOST"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DB"),
            "USER": os.getenv("POSTGRES_USER"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
            "HOST": os.getenv("POSTGRES_HOST"),
            "PORT": os.getenv("POSTGRES_PORT", "5432"),
        }
    }
elif APP_ENV == "development":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    raise RuntimeError(
        "No database configuration found. Set DATABASE_URL, provide "
        "PGHOST/PGDATABASE/PGUSER/PGPASSWORD, provide POSTGRES_* variables, "
        "or use APP_ENV=development for local SQLite."
    )

print("DB ENGINE:", DATABASES["default"]["ENGINE"])
print("DB HOST:", DATABASES["default"].get("HOST"))


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CELERY_BROKER_URL = os.getenv(
    "CELERY_BROKER_URL",
    os.getenv("REDIS_URL", "redis://redis:6379/0"),
)
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", CELERY_BROKER_URL)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_IMPORTS = ("api.tasks",)
CELERY_TIMEZONE = TIME_ZONE
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"
CELERY_WORKER_CONCURRENCY = int(os.getenv("CELERY_WORKER_CONCURRENCY", "2"))
# DatabaseScheduler reads its periodic task rows from django-celery-beat.
# The schedule itself is synced into the database by the sync_*_schedule commands.
TRADING_VIEW_SCRAPE_START_TIME_UTC = os.getenv("TRADING_VIEW_SCRAPE_START_TIME_UTC", "13:00")
TRADING_VIEW_SCRAPE_END_TIME_UTC = os.getenv("TRADING_VIEW_SCRAPE_END_TIME_UTC", "20:00")
TRADING_VIEW_SCRAPE_INTERVAL_MINUTES = int(
    os.getenv("TRADING_VIEW_SCRAPE_INTERVAL_MINUTES", "45")
)
INITIAL_SCREENER_TIME_UTC = os.getenv("INITIAL_SCREENER_TIME_UTC", "12:30")
POPULATE_DAILY_BRIEF_TIME_UTC = os.getenv(
    "POPULATE_DAILY_BRIEF_TIME_UTC",
    "14:30,15:30,16:30,17:30,18:30,19:30,20:00",
)
DAILY_BRIEF_SEND_HOUR_UTC = int(os.getenv("DAILY_BRIEF_SEND_HOUR_UTC", "17"))
DAILY_BRIEF_SEND_MINUTE_UTC = int(os.getenv("DAILY_BRIEF_SEND_MINUTE_UTC", "30"))
